import { cleanup, render, screen } from '@testing-library/react'
import { afterEach, beforeAll, describe, expect, it } from 'vitest'
import type { DnsInfo } from '@shared/types'
import { i18n, initRendererI18n } from '@renderer/i18n'
import DnsBlock, { dnsVerdict } from '@renderer/dashboard/DnsBlock'

function dns(over: Partial<DnsInfo> = {}): DnsInfo {
  return {
    resolvConfPath: '/etc/resolv.conf',
    isGeneratedSymlink: true,
    generateResolvConf: true,
    dnsTunneling: false,
    nameservers: ['172.20.0.1'],
    windowsAdapterDns: ['192.168.1.1'],
    error: null,
    ...over
  }
}

/** The configuration that quietly stops working: edited file, generation off. */
const STALE = dns({
  isGeneratedSymlink: false,
  generateResolvConf: false,
  nameservers: ['10.255.255.254'],
  windowsAdapterDns: ['192.168.1.1', '1.1.1.1']
})

function verdictText(): string {
  return document.querySelector('[data-verdict]')?.textContent ?? ''
}

beforeAll(async () => {
  initRendererI18n('en')
  if (!i18n.isInitialized) {
    await new Promise<void>((resolve) => {
      i18n.on('initialized', () => resolve())
    })
  }
})

afterEach(() => {
  cleanup()
})

describe('dnsVerdict', () => {
  it('states nothing at all when the read was incomplete', () => {
    expect(dnsVerdict(dns({ error: 'The Windows DNS servers could not be read' }))).toBeNull()
    expect(
      dnsVerdict(
        dns({
          nameservers: [],
          error: '/etc/resolv.conf could not be read inside the distribution'
        })
      )
    ).toBeNull()
  })

  it('states nothing when a healthy generated resolver needs no explanation', () => {
    expect(dnsVerdict(dns())).toBeNull()
  })

  it('leads with an empty resolver file, whatever else is set', () => {
    expect(dnsVerdict(dns({ nameservers: [], dnsTunneling: true }))).toBe('no-nameservers')
  })

  it('warns that WSL will overwrite a hand-written file it still generates', () => {
    expect(dnsVerdict(dns({ isGeneratedSymlink: false, generateResolvConf: true }))).toBe(
      'will-overwrite'
    )
  })

  it('separates a stale file Windows disagrees with from one that merely stopped updating', () => {
    expect(dnsVerdict(STALE)).toBe('stale-mismatch')
    expect(dnsVerdict({ ...STALE, windowsAdapterDns: ['10.255.255.254'] })).toBe('stale')
    expect(dnsVerdict({ ...STALE, windowsAdapterDns: [] })).toBe('stale')
  })

  it('explains tunneling only when nothing worse is happening', () => {
    expect(dnsVerdict(dns({ dnsTunneling: true }))).toBe('tunneling')
    expect(
      dnsVerdict(dns({ dnsTunneling: true, isGeneratedSymlink: false, generateResolvConf: true }))
    ).toBe('will-overwrite')
  })

  it('says nothing about a file whose shape could not be classified', () => {
    expect(dnsVerdict(dns({ isGeneratedSymlink: null, dnsTunneling: null }))).toBeNull()
  })
})

describe('DnsBlock', () => {
  it('shows every fact behind the verdict', () => {
    render(<DnsBlock dns={STALE} />)
    expect(screen.getByText('Name resolution')).toBeTruthy()
    expect(screen.getByText('/etc/resolv.conf')).toBeTruthy()
    expect(screen.getByText('10.255.255.254')).toBeTruthy()
    expect(screen.getByText('192.168.1.1, 1.1.1.1')).toBeTruthy()
    expect(screen.getByText('Generated by WSL')).toBeTruthy()
    expect(screen.getByText('generateResolvConf')).toBeTruthy()
    expect(screen.getByText('DNS tunneling')).toBeTruthy()
  })

  it('names the cause of a resolver Windows no longer feeds', () => {
    render(<DnsBlock dns={STALE} />)
    expect(verdictText()).toContain('not the ones Windows hands out')
    expect(verdictText()).toContain('/etc/resolv.conf')
  })

  it('says the next start will overwrite a hand-written file', () => {
    render(<DnsBlock dns={dns({ isGeneratedSymlink: false, generateResolvConf: true })} />)
    expect(verdictText()).toContain('will overwrite it the next time this distribution starts')
  })

  it('says an empty resolver file is why every lookup fails', () => {
    render(<DnsBlock dns={dns({ nameservers: [] })} />)
    expect(verdictText()).toContain('temporary failure in name resolution')
    expect(screen.getByText('None')).toBeTruthy()
  })

  it('draws no conclusion from an incomplete read, and shows the failure', () => {
    render(<DnsBlock dns={dns({ error: 'The Windows DNS servers could not be read' })} />)
    expect(document.querySelector('[data-verdict]')).toBeNull()
    expect(screen.getByText('The Windows DNS servers could not be read')).toBeTruthy()
  })

  it('shows unknown facts as unknown rather than as no and none', () => {
    render(
      <DnsBlock
        dns={dns({
          isGeneratedSymlink: null,
          generateResolvConf: null,
          dnsTunneling: null,
          nameservers: [],
          windowsAdapterDns: [],
          error: 'read failed'
        })}
      />
    )
    expect(screen.getAllByText('Unknown')).toHaveLength(3)
    expect(screen.getAllByText('None')).toHaveLength(2)
  })

  it('reports a resolver it could not read at all', () => {
    render(<DnsBlock dns={null} />)
    expect(screen.getByText('The resolver configuration could not be read.')).toBeTruthy()
    expect(document.querySelector('[data-verdict]')).toBeNull()
  })
})
