import type { ReactNode } from 'react'
import { useTranslation } from 'react-i18next'
import type { DnsInfo } from '@shared/types'

function Kv({
  k,
  mono,
  children
}: {
  k: string
  mono?: boolean
  children: ReactNode
}): React.JSX.Element {
  return (
    <div className="kv-row">
      <span className="kv-key">{k}</span>
      <span className={mono ? 'kv-val mono' : 'kv-val'}>{children}</span>
    </div>
  )
}

/**
 * The one sentence the four facts add up to. Ordered by what actually breaks
 * resolution first, and every branch is a statement the data supports: a
 * partial read (error set) supports nothing at all, so it yields no verdict.
 */
export type DnsVerdict =
  'no-nameservers' | 'will-overwrite' | 'stale-mismatch' | 'stale' | 'tunneling'

export function dnsVerdict(dns: DnsInfo): DnsVerdict | null {
  if (dns.error !== null) return null
  if (dns.nameservers.length === 0) return 'no-nameservers'
  const handWritten = dns.isGeneratedSymlink === false
  if (handWritten && dns.generateResolvConf === true) return 'will-overwrite'
  if (handWritten && dns.generateResolvConf === false) {
    const unlisted = dns.windowsAdapterDns.filter((s) => !dns.nameservers.includes(s))
    return unlisted.length > 0 ? 'stale-mismatch' : 'stale'
  }
  if (dns.dnsTunneling === true) return 'tunneling'
  return null
}

export interface DnsBlockProps {
  dns: DnsInfo | null
}

/**
 * Name resolution as one block (issue #35): what /etc/resolv.conf is, whether
 * WSL still generates it, whether DNS tunneling is on, the servers in force and
 * the ones Windows hands out — then the verdict those four add up to, or no
 * verdict at all. Read-only: nothing here rewrites the resolver.
 */
export default function DnsBlock({ dns }: DnsBlockProps): React.JSX.Element {
  const { t } = useTranslation()

  const yesNoUnknown = (value: boolean | null): ReactNode =>
    value === null ? (
      <span className="dim">{t('common.unknown')}</span>
    ) : value ? (
      t('common.yes')
    ) : (
      t('common.no')
    )

  const list = (values: string[]): ReactNode =>
    values.length === 0 ? <span className="dim">{t('common.none')}</span> : values.join(', ')

  const heading = (
    <div className="path-label">
      {t('dashboard.network.dns', { defaultValue: 'Name resolution' })}
    </div>
  )

  if (dns === null) {
    return (
      <>
        {heading}
        <div className="dim">
          {t('dashboard.network.dnsUnknown', {
            defaultValue: 'The resolver configuration could not be read.'
          })}
        </div>
      </>
    )
  }

  const verdict = dnsVerdict(dns)
  const path = dns.resolvConfPath
  const sentence = (): ReactNode => {
    switch (verdict) {
      case 'no-nameservers':
        return t('dashboard.network.dnsVerdictNoNameservers', {
          defaultValue:
            '{{path}} lists no nameserver, so every lookup fails with a temporary failure in name resolution.',
          path
        })
      case 'will-overwrite':
        return t('dashboard.network.dnsVerdictWillOverwrite', {
          defaultValue:
            '{{path}} was written by hand while generateResolvConf is still on, so WSL will overwrite it the next time this distribution starts.',
          path
        })
      case 'stale-mismatch':
        return t('dashboard.network.dnsMismatch', { path })
      case 'stale':
        return t('dashboard.network.dnsVerdictStale', {
          defaultValue:
            'generateResolvConf is off, so WSL no longer maintains {{path}}: the servers in it stay as written even after the network changes.',
          path
        })
      case 'tunneling':
        return t('dashboard.network.dnsVerdictTunneling', {
          defaultValue:
            'DNS tunneling is on, so lookups are answered by the Windows resolver rather than sent to the servers listed here.'
        })
      default:
        return null
    }
  }

  return (
    <>
      {heading}
      {dns.error !== null ? (
        <div className="kv-row">
          <span className="badge badge-warn">{t('common.warning')}</span>
          <span className="kv-val dim">{dns.error}</span>
        </div>
      ) : null}
      {verdict === null ? null : verdict === 'tunneling' ? (
        <div className="kv-row dim" data-verdict={verdict}>
          {sentence()}
        </div>
      ) : (
        <div className="overview-head" data-verdict={verdict}>
          <span>{sentence()}</span>
        </div>
      )}
      <Kv k={t('dashboard.network.resolvConf', { defaultValue: 'Resolver file' })} mono>
        {path}
      </Kv>
      <Kv k={t('dashboard.network.generatedSymlink', { defaultValue: 'Generated by WSL' })}>
        {yesNoUnknown(dns.isGeneratedSymlink)}
      </Kv>
      <Kv k={t('dashboard.network.generateResolvConf', { defaultValue: 'generateResolvConf' })}>
        {yesNoUnknown(dns.generateResolvConf)}
      </Kv>
      <Kv k={t('dashboard.network.dnsTunneling', { defaultValue: 'DNS tunneling' })}>
        {yesNoUnknown(dns.dnsTunneling)}
      </Kv>
      <Kv k={t('dashboard.network.nameservers', { defaultValue: 'Nameservers in use' })} mono>
        {list(dns.nameservers)}
      </Kv>
      <Kv k={t('dashboard.network.windowsDns', { defaultValue: 'Windows adapter DNS' })} mono>
        {list(dns.windowsAdapterDns)}
      </Kv>
    </>
  )
}
