import { describe, expect, it, vi } from 'vitest'
import {
  createDnsCollector,
  DNS_SCRIPT,
  parseDnsFacts,
  parseNameservers,
  parseWindowsDnsServers,
  RESOLV_CONF_PATH,
  type DistroDnsFacts
} from '../../../src/main/wsl/dns'
import { WslNotAvailableError, type DistroRunner } from '../../../src/main/wsl/contracts'
import type { HostCommandRunner } from '../../../src/main/wsl/windows-ports'
import { fakeRunner, joinSections, ok } from './collectors/helpers'

const GENERATED_HEADER =
  '# This file was automatically generated by WSL. To stop automatic generation of this file,'

/** The five sections DNS_SCRIPT prints, in order. */
function distroOutput(
  kind: string,
  target: string,
  resolvConf: string,
  wslConfState: string,
  wslConf: string
): string {
  return joinSections(kind, target, resolvConf, wslConfState, wslConf)
}

const GENERATED = distroOutput(
  'symlink',
  '/mnt/wsl/resolv.conf',
  `${GENERATED_HEADER}\nnameserver 172.20.0.1\n`,
  'missing',
  ''
)

const HAND_EDITED = distroOutput(
  'file',
  '',
  'nameserver 10.255.255.254\n',
  'readable',
  '[network]\ngenerateResolvConf = false\n'
)

const PS_OUTPUT = ['192.168.1.1', '1.1.1.1', '192.168.1.1', '', 'fe80::1', 'garbage'].join('\r\n')

interface Harness {
  run: HostCommandRunner
  calls: string[]
}

function hostRunner(result: () => string): Harness {
  const calls: string[] = []
  const run: HostCommandRunner = async (file) => {
    calls.push(file)
    return result()
  }
  return { run, calls }
}

function throwingRunner(err: unknown): DistroRunner {
  return fakeRunner(() => {
    throw err
  })
}

describe('parseNameservers', () => {
  it('keeps declaration order, drops comments and duplicates', () => {
    const text = [
      '# generated',
      'nameserver 10.255.255.254',
      '; nameserver 9.9.9.9',
      'search lan',
      'nameserver 1.1.1.1',
      'nameserver 10.255.255.254',
      'options edns0'
    ].join('\n')
    expect(parseNameservers(text)).toEqual(['10.255.255.254', '1.1.1.1'])
  })

  it('returns nothing for a file that declares nothing', () => {
    expect(parseNameservers('search lan\n')).toEqual([])
  })
})

describe('parseWindowsDnsServers', () => {
  it('takes the IPv4 lines positionally and ignores everything else', () => {
    expect(parseWindowsDnsServers(PS_OUTPUT)).toEqual(['192.168.1.1', '1.1.1.1'])
  })

  it('rejects a dotted quad with an impossible octet', () => {
    expect(parseWindowsDnsServers('999.1.1.1\n10.0.0.1\n')).toEqual(['10.0.0.1'])
  })
})

/** parseDnsFacts for the cases that do parse; the null case is its own test. */
function facts(text: string): DistroDnsFacts {
  const parsed = parseDnsFacts(text)
  if (parsed === null) throw new Error('expected this script output to parse')
  return parsed
}

describe('parseDnsFacts', () => {
  it('recognizes WSL\u2019s own symlink and the default it implies', () => {
    const parsed = facts(GENERATED)
    expect(parsed.isGeneratedSymlink).toBe(true)
    // No /etc/wsl.conf at all: the documented default is the effective value.
    expect(parsed.generateResolvConf).toBe(true)
    expect(parsed.nameservers).toEqual(['172.20.0.1'])
  })

  it('recognizes a hand-written file with generation turned off', () => {
    const parsed = facts(HAND_EDITED)
    expect(parsed.isGeneratedSymlink).toBe(false)
    expect(parsed.generateResolvConf).toBe(false)
    expect(parsed.nameservers).toEqual(['10.255.255.254'])
  })

  it('counts a plain file carrying WSL\u2019s header as generated', () => {
    const parsed = facts(
      distroOutput('file', '', `${GENERATED_HEADER}\nnameserver 172.20.0.1\n`, 'missing', '')
    )
    expect(parsed.isGeneratedSymlink).toBe(true)
  })

  it('does not credit WSL with a symlink into someone else\u2019s file', () => {
    const parsed = facts(
      distroOutput(
        'symlink',
        '/run/systemd/resolve/stub-resolv.conf',
        'nameserver 127.0.0.53\n',
        'missing',
        ''
      )
    )
    expect(parsed.isGeneratedSymlink).toBe(false)
  })

  it('reports a missing resolver file as no file and no servers', () => {
    const parsed = facts(distroOutput('missing', '', '', 'missing', ''))
    expect(parsed.isGeneratedSymlink).toBe(false)
    expect(parsed.nameservers).toEqual([])
  })

  it('leaves generateResolvConf unknown when wsl.conf cannot be read', () => {
    const parsed = facts(distroOutput('file', '', 'nameserver 1.1.1.1\n', 'unreadable', ''))
    expect(parsed.generateResolvConf).toBeNull()
  })

  it('takes the last declaration and rejects a value that is not a boolean', () => {
    const later = facts(
      distroOutput(
        'file',
        '',
        'nameserver 1.1.1.1\n',
        'readable',
        '[network]\ngenerateResolvConf = false\ngenerateResolvConf = true\n'
      )
    )
    expect(later.generateResolvConf).toBe(true)

    const nonsense = facts(
      distroOutput(
        'file',
        '',
        'nameserver 1.1.1.1\n',
        'readable',
        '[network]\ngenerateResolvConf=maybe\n'
      )
    )
    expect(nonsense.generateResolvConf).toBeNull()
  })

  it('reads output that answered nothing as a failed read, not as an empty resolver', () => {
    expect(parseDnsFacts('')).toBeNull()
    expect(parseDnsFacts('/bin/sh: 1: Syntax error\n')).toBeNull()
  })

  it('ignores the key when it sits in the wrong section', () => {
    const parsed = facts(
      distroOutput(
        'file',
        '',
        'nameserver 1.1.1.1\n',
        'readable',
        '[boot]\ngenerateResolvConf=false\n'
      )
    )
    expect(parsed.generateResolvConf).toBe(true)
  })
})

describe('createDnsCollector', () => {
  it('joins both sides of the boundary into one answer', async () => {
    const host = hostRunner(() => PS_OUTPUT)
    const runner = fakeRunner(() => ok(HAND_EDITED))
    const dns = await createDnsCollector({
      run: host.run,
      userProfile: 'C:\\Users\\dev',
      readWindowsFile: async () => '[wsl2]\ndnsTunneling=true\n'
    }).collect(runner, 'Ubuntu-24.04')

    expect(runner.calls[0]).toBe(DNS_SCRIPT)
    expect(dns).toEqual({
      resolvConfPath: RESOLV_CONF_PATH,
      isGeneratedSymlink: false,
      generateResolvConf: false,
      dnsTunneling: true,
      nameservers: ['10.255.255.254'],
      windowsAdapterDns: ['192.168.1.1', '1.1.1.1'],
      error: null
    })
  })

  it('leaves dnsTunneling unknown when the key is undeclared or the profile is not known', async () => {
    const host = hostRunner(() => '')
    const readWindowsFile = vi.fn(async () => '[wsl2]\nmemory=8GB\n')
    const undeclared = await createDnsCollector({
      run: host.run,
      userProfile: 'C:\\Users\\dev',
      readWindowsFile
    }).collect(
      fakeRunner(() => ok(GENERATED)),
      'Ubuntu-24.04'
    )
    expect(undeclared.dnsTunneling).toBeNull()

    const noProfile = await createDnsCollector({
      run: host.run,
      userProfile: null,
      readWindowsFile
    }).collect(
      fakeRunner(() => ok(GENERATED)),
      'Ubuntu-24.04'
    )
    expect(noProfile.dnsTunneling).toBeNull()
    expect(readWindowsFile).toHaveBeenCalledTimes(1)
  })

  it('keeps the distro side when the Windows query fails', async () => {
    const host: HostCommandRunner = async () => {
      throw new Error('powershell.exe timed out after 8000ms')
    }
    const dns = await createDnsCollector({
      run: host,
      userProfile: null,
      readWindowsFile: async () => null
    }).collect(
      fakeRunner(() => ok(HAND_EDITED)),
      'Ubuntu-24.04'
    )
    expect(dns.nameservers).toEqual(['10.255.255.254'])
    // Empty must never read as "the adapter hands out nothing".
    expect(dns.windowsAdapterDns).toEqual([])
    expect(dns.error).toBe('The Windows DNS servers could not be read')
  })

  it('keeps the Windows side when the distro side fails', async () => {
    const host = hostRunner(() => PS_OUTPUT)
    const dns = await createDnsCollector({
      run: host.run,
      userProfile: null,
      readWindowsFile: async () => null
    }).collect(throwingRunner(new Error('exit 1')), 'Ubuntu-24.04')

    expect(dns.isGeneratedSymlink).toBeNull()
    expect(dns.generateResolvConf).toBeNull()
    expect(dns.nameservers).toEqual([])
    expect(dns.windowsAdapterDns).toEqual(['192.168.1.1', '1.1.1.1'])
    expect(dns.error).toContain(RESOLV_CONF_PATH)
  })

  it('names both failures when neither side could be read', async () => {
    const host: HostCommandRunner = async () => {
      throw new Error('nope')
    }
    const dns = await createDnsCollector({
      run: host,
      userProfile: null,
      readWindowsFile: async () => null
    }).collect(
      fakeRunner(() => ({ stdout: '', stderr: '', code: null, timedOut: true })),
      'Ubuntu-24.04'
    )
    expect(dns.error).toBe(
      `${RESOLV_CONF_PATH} could not be read inside the distribution; ` +
        'The Windows DNS servers could not be read'
    )
  })

  it('reuses the Windows answer inside its TTL and re-reads after it', async () => {
    const host = hostRunner(() => PS_OUTPUT)
    let clock = 1000
    const collector = createDnsCollector({
      run: host.run,
      userProfile: null,
      readWindowsFile: async () => null,
      ttlMs: 30000,
      now: () => clock
    })
    const runner = fakeRunner(() => ok(GENERATED))
    await collector.collect(runner, 'Ubuntu-24.04')
    clock += 15000
    await collector.collect(runner, 'Ubuntu-24.04')
    expect(host.calls).toEqual(['powershell.exe'])
    // The distro side is not cached: it is cheap and it is what changes.
    expect(runner.calls).toHaveLength(2)

    clock += 20000
    await collector.collect(runner, 'Ubuntu-24.04')
    expect(host.calls).toHaveLength(2)
  })

  it('propagates a missing WSL and rejects an invalid distro name', async () => {
    const collector = createDnsCollector({
      run: hostRunner(() => '').run,
      userProfile: null,
      readWindowsFile: async () => null
    })
    await expect(
      collector.collect(throwingRunner(new WslNotAvailableError()), 'Ubuntu-24.04')
    ).rejects.toBeInstanceOf(WslNotAvailableError)
    await expect(
      collector.collect(
        fakeRunner(() => ok('')),
        'bad name'
      )
    ).rejects.toThrow(/Invalid WSL distro name/)
  })
})
