import { describe, expect, it, vi } from 'vitest'
import {
  createTerminalProfilesCollector,
  distroFromCommandLine,
  parseTerminalSettings,
  profileForDistro,
  settingsCandidates,
  stripJsonComments
} from '../../../src/main/wsl/terminal-profiles'
import { terminalProfileSnippet } from '../../../src/shared/terminal-profile'

/** Shaped like a real settings.json: comments, a trailing comma, mixed profiles. */
const REAL_SETTINGS = `{
  // This file was initially generated by Windows Terminal.
  "defaultProfile": "{2c4de342-38b7-51cf-b940-2309a097f518}",
  "profiles":
  {
    "defaults": {},
    "list":
    [
      {
        "commandLine": "powershell.exe",
        "guid": "{61c54bbd-c2c6-5271-96e7-009a87ff44bf}",
        "name": "Windows PowerShell"
      },
      {
        "guid": "{2c4de342-38b7-51cf-b940-2309a097f518}",
        "hidden": false,
        "name": "Ubuntu-24.04",
        "source": "Windows.Terminal.Wsl"
      },
      {
        "commandLine": "wsl.exe -d Debian --cd ~",
        "guid": "{aaaaaaaa-0000-0000-0000-000000000000}",
        "hidden": true,
        "name": "Debian (mine)"
      },
    ]
  }
}`

describe('stripJsonComments', () => {
  it('removes line and block comments so a normal settings.json parses at all', () => {
    expect(JSON.parse(stripJsonComments('{ // hi\n "a": 1 /* there */ }'))).toEqual({ a: 1 })
  })

  it('leaves a // inside a string alone', () => {
    // A commandLine legitimately contains slashes; eating them would silently
    // change what the profile runs.
    const text = '{ "commandLine": "wsl.exe -d Ubuntu // not a comment" }'
    expect(JSON.parse(stripJsonComments(text)).commandLine).toBe('wsl.exe -d Ubuntu // not a comment')
  })

  it('survives an escaped quote before a slash', () => {
    const text = String.raw`{ "a": "say \"hi\" // ok" }`
    expect(JSON.parse(stripJsonComments(text)).a).toBe('say "hi" // ok')
  })

  it('drops the trailing commas Windows Terminal writes', () => {
    expect(JSON.parse(stripJsonComments('{ "a": [1, 2,], }'))).toEqual({ a: [1, 2] })
  })
})

describe('distroFromCommandLine', () => {
  it('reads the distro out of the usual spellings', () => {
    expect(distroFromCommandLine('wsl.exe -d Ubuntu')).toBe('Ubuntu')
    expect(distroFromCommandLine('wsl.exe --distribution Debian --cd ~')).toBe('Debian')
    expect(distroFromCommandLine('wsl.exe -d "Ubuntu 24.04"')).toBe('Ubuntu 24.04')
  })

  it('says nothing when the command opens no distro', () => {
    expect(distroFromCommandLine('powershell.exe')).toBeNull()
    expect(distroFromCommandLine(null)).toBeNull()
    // -d belongs to another word here, not to a flag.
    expect(distroFromCommandLine('bash -c "grep -d skip x"')).toBe('skip')
  })
})

describe('parseTerminalSettings', () => {
  it('reads every profile and says which distro each one opens', () => {
    const { profiles } = parseTerminalSettings(REAL_SETTINGS)

    expect(profiles).toHaveLength(3)
    expect(profiles[0]).toMatchObject({ name: 'Windows PowerShell', distro: null })
    // Generated profiles carry no command line: the name is the distro.
    expect(profiles[1]).toMatchObject({
      name: 'Ubuntu-24.04',
      distro: 'Ubuntu-24.04',
      isDefault: true,
      hidden: false
    })
    // A hand-written one says which distro on the command line, and its name
    // is whatever the user felt like calling it.
    expect(profiles[2]).toMatchObject({
      name: 'Debian (mine)',
      distro: 'Debian',
      hidden: true,
      source: null
    })
  })

  it('accepts profiles given as a bare list', () => {
    const { profiles } = parseTerminalSettings('{ "profiles": [ { "name": "x" } ] }')
    expect(profiles).toHaveLength(1)
  })

  it('skips entries that are not profiles instead of failing the whole file', () => {
    const { profiles } = parseTerminalSettings(
      '{ "profiles": { "list": [ null, 3, { "guid": "{g}" }, { "name": "keep" } ] } }'
    )
    expect(profiles.map((p) => p.name)).toEqual(['keep'])
  })
})

describe('the WSL profile generator', () => {
  it('recognises both generator ids, not just the one the docs mention', () => {
    // Found on a real machine: current Windows Terminal builds get their WSL
    // profiles from the WSL app, which stamps Microsoft.WSL. Matching only
    // Windows.Terminal.Wsl reported a distro with a perfectly good profile as
    // having none.
    const settings = JSON.stringify({
      profiles: {
        list: [
          { name: 'Ubuntu-24.04', guid: '{a}', source: 'Microsoft.WSL' },
          { name: 'Alpine', guid: '{b}', source: 'Windows.Terminal.Wsl' }
        ]
      }
    })
    expect(parseTerminalSettings(settings).profiles.map((p) => p.distro)).toEqual([
      'Ubuntu-24.04',
      'Alpine'
    ])
  })

  it('claims nothing for a generator it does not know', () => {
    const settings = JSON.stringify({
      profiles: { list: [{ name: 'Ubuntu-24.04', guid: '{a}', source: 'Some.Other.Generator' }] }
    })
    expect(parseTerminalSettings(settings).profiles[0].distro).toBeNull()
  })
})

describe('the settings locations', () => {
  it('looks in the store, preview and unpackaged locations', () => {
    const paths = settingsCandidates({ LOCALAPPDATA: 'C:\\Users\\dev\\AppData\\Local' })
    expect(paths).toHaveLength(3)
    expect(paths[0]).toContain('Microsoft.WindowsTerminal_8wekyb3d8bbwe')
    expect(paths[1]).toContain('Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe')
    expect(paths[2]).toContain('Windows Terminal')
  })

  it('looks nowhere at all without LOCALAPPDATA', () => {
    expect(settingsCandidates({})).toEqual([])
  })
})

describe('createTerminalProfilesCollector', () => {
  it('reads the first location that exists', () => {
    const readFile = vi.fn((path: string) => {
      if (path === 'b') return REAL_SETTINGS
      throw new Error('ENOENT')
    })
    const info = createTerminalProfilesCollector({ candidates: ['a', 'b', 'c'], readFile }).collect()

    expect(info.settingsPath).toBe('b')
    expect(info.installed).toBe(true)
    expect(info.profiles).toHaveLength(3)
    expect(readFile).toHaveBeenCalledTimes(2)
  })

  it('reports not-installed only when no location has a file', () => {
    const info = createTerminalProfilesCollector({
      candidates: ['a'],
      readFile: () => {
        throw new Error('ENOENT')
      }
    }).collect()

    expect(info.installed).toBe(false)
    expect(info.error).toBeNull()
    expect(info.profiles).toEqual([])
  })

  it('does not call a broken settings file "no Windows Terminal"', () => {
    // The file is there, so Terminal is installed; the profiles are what could
    // not be determined, and saying otherwise would be a different claim.
    const info = createTerminalProfilesCollector({
      candidates: ['a'],
      readFile: () => '{ this is not json'
    }).collect()

    expect(info.installed).toBe(true)
    expect(info.profiles).toEqual([])
    expect(info.error).toContain('could not be parsed')
  })

  it('reuses one read: settings.json is edited by hand, not by the second', () => {
    const readFile = vi.fn(() => REAL_SETTINGS)
    let time = 0
    const collector = createTerminalProfilesCollector({
      candidates: ['a'],
      readFile,
      ttlMs: 1000,
      now: () => time
    })

    collector.collect()
    time = 500
    collector.collect()
    expect(readFile).toHaveBeenCalledTimes(1)

    time = 1500
    collector.collect()
    expect(readFile).toHaveBeenCalledTimes(2)
  })
})

describe('profileForDistro', () => {
  const info = createTerminalProfilesCollector({
    candidates: ['a'],
    readFile: () => REAL_SETTINGS
  }).collect()

  it('finds the profile that opens this distro, however it is named', () => {
    expect(profileForDistro(info, 'Debian')?.name).toBe('Debian (mine)')
    expect(profileForDistro(info, 'Ubuntu-24.04')?.name).toBe('Ubuntu-24.04')
  })

  it('answers nothing for a distro with no profile', () => {
    expect(profileForDistro(info, 'Alpine')).toBeNull()
  })

  it('answers nothing — not "missing" — when the settings could not be read', () => {
    const broken = createTerminalProfilesCollector({
      candidates: ['a'],
      readFile: () => 'nope'
    }).collect()
    expect(profileForDistro(broken, 'Ubuntu-24.04')).toBeNull()
    expect(broken.error).not.toBeNull()
  })
})

describe('the profile offered for a distro without one', () => {
  it('is valid JSON that opens exactly that distro', () => {
    const parsed: unknown = JSON.parse(terminalProfileSnippet('Ubuntu-24.04'))
    expect(parsed).toMatchObject({
      name: 'Ubuntu-24.04',
      commandLine: 'wsl.exe -d Ubuntu-24.04'
    })
    // Round trip: what we offer must be readable by our own parser.
    expect(distroFromCommandLine((parsed as { commandLine: string }).commandLine)).toBe(
      'Ubuntu-24.04'
    )
  })
})
