/**
 * Why name resolution works, or does not (issue #35).
 *
 * "Temporary failure in name resolution" has its cause spread over four places
 * nobody checks together: what /etc/resolv.conf actually is, whether WSL still
 * generates it, whether DNS tunneling is on, and what the Windows adapter is
 * handing out. This collector reads all four and reports them side by side —
 * it never rewrites resolv.conf and never restarts anything.
 */
import { readFile } from 'fs/promises'
import { RUNNER_TIMEOUT_MS } from '@shared/constants'
import type { DnsInfo } from '@shared/types'
import { WslNotAvailableError, type DistroRunner } from './contracts'
import { assertValidDistroName } from './escape'
import { SECTION_MARKER, splitSections } from './system'
import { decodeConfigFile, normalizeBool, parseIni, WSL_CONF_PATH } from './wsl-config'
import { runHostCommand, type HostCommandRunner } from './windows-ports'

export const RESOLV_CONF_PATH = '/etc/resolv.conf'

const POWERSHELL_TIMEOUT_MS = 8000

/** WSL's own file, whether it is the symlink target or the header it writes. */
const WSL_MANAGED_TARGET_RE = /^\/mnt\/wsl\//
const GENERATED_HEADER_RE = /automatically generated by WSL/i

const NAMESERVER_RE = /^nameserver\s+(\S+)/i
const IPV4_RE = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/

const marker = `printf '\\n${SECTION_MARKER}\\n'`

// One round trip: the kind of resolv.conf, its link target, its content, and
// whether wsl.conf is readable at all before its content. Readability is asked
// separately so a file that exists but cannot be read stays unknown instead of
// silently reading as "the default applies".
export const DNS_SCRIPT = [
  `if [ -L ${RESOLV_CONF_PATH} ]; then echo symlink; ` +
    `elif [ -f ${RESOLV_CONF_PATH} ]; then echo file; ` +
    `elif [ -e ${RESOLV_CONF_PATH} ]; then echo other; else echo missing; fi`,
  marker,
  `readlink ${RESOLV_CONF_PATH} 2>/dev/null || true`,
  marker,
  `cat ${RESOLV_CONF_PATH} 2>/dev/null || true`,
  marker,
  `if [ ! -e ${WSL_CONF_PATH} ]; then echo missing; ` +
    `elif [ -r ${WSL_CONF_PATH} ]; then echo readable; else echo unreadable; fi`,
  marker,
  `cat ${WSL_CONF_PATH} 2>/dev/null || true`
].join('\n')

function firstLine(section: string | undefined): string | null {
  if (section === undefined) return null
  for (const line of section.split('\n')) {
    const trimmed = line.trim()
    if (trimmed !== '') return trimmed
  }
  return null
}

/** nameserver lines in file order, deduplicated; comments and junk ignored. */
export function parseNameservers(text: string): string[] {
  const out: string[] = []
  for (const raw of text.split('\n')) {
    const line = raw.trim()
    if (line === '' || line.startsWith('#') || line.startsWith(';')) continue
    const match = NAMESERVER_RE.exec(line)
    if (match === null) continue
    if (!out.includes(match[1])) out.push(match[1])
  }
  return out
}

/** Last declaration of an ini key wins, matching how the file is read top-down. */
function lastValue(text: string, section: string, key: string): string | null {
  const lower = key.toLowerCase()
  let found: string | null = null
  for (const entry of parseIni(text)) {
    if (entry.section === section && entry.key.toLowerCase() === lower) found = entry.value
  }
  return found
}

function boolValue(text: string, section: string, key: string): boolean | null {
  const value = lastValue(text, section, key)
  if (value === null) return null
  const normalized = normalizeBool(value)
  return normalized === null ? null : normalized === 'true'
}

/**
 * generateResolvConf as it actually applies. An absent /etc/wsl.conf declares
 * nothing, so WSL's documented default holds; a file that cannot be read might
 * declare anything, and a key written with something that is not a boolean word
 * is not readable either — both of those stay unknown rather than defaulting.
 */
function effectiveGenerateResolvConf(state: string | null, wslConf: string): boolean | null {
  if (state === 'missing') return true
  if (state !== 'readable') return null
  const declared = lastValue(wslConf, 'network', 'generateResolvConf')
  if (declared === null) return true
  const normalized = normalizeBool(declared)
  return normalized === null ? null : normalized === 'true'
}

export interface DistroDnsFacts {
  isGeneratedSymlink: boolean | null
  generateResolvConf: boolean | null
  nameservers: string[]
}

const RESOLV_KINDS = ['symlink', 'file', 'other', 'missing']

/**
 * The distro half of the answer. `isGeneratedSymlink` follows the file itself:
 * a link into /mnt/wsl is WSL's, a plain file carrying WSL's header was written
 * by WSL too, and anything else — including a file that is simply not there —
 * is not. A shape that cannot be classified stays null.
 *
 * Output that does not even carry the first answer means the script did not run
 * (null), never a resolver with nothing in it: "no nameservers" is a diagnosis,
 * and it must not be reachable by failing to read the file.
 */
export function parseDnsFacts(text: string): DistroDnsFacts | null {
  const sections = splitSections(text)
  const kind = firstLine(sections[0])
  if (kind === null || !RESOLV_KINDS.includes(kind)) return null
  const target = firstLine(sections[1])
  const resolvConf = sections[2] ?? ''
  const wslConfState = firstLine(sections[3])
  const wslConf = sections[4] ?? ''

  let isGeneratedSymlink: boolean | null = null
  if (kind === 'symlink') isGeneratedSymlink = target !== null && WSL_MANAGED_TARGET_RE.test(target)
  else if (kind === 'file') isGeneratedSymlink = GENERATED_HEADER_RE.test(resolvConf)
  else if (kind === 'missing') isGeneratedSymlink = false

  return {
    isGeneratedSymlink,
    generateResolvConf: effectiveGenerateResolvConf(wslConfState, wslConf),
    nameservers: kind === 'missing' ? [] : parseNameservers(resolvConf)
  }
}

/**
 * Windows DNS servers, parsed positionally: the query is asked for addresses
 * only, so every line that is an IPv4 address is one and every other line is
 * ignored. Nothing depends on a localized label.
 */
export function parseWindowsDnsServers(text: string): string[] {
  const out: string[] = []
  for (const raw of text.split('\n')) {
    const line = raw.trim()
    const match = IPV4_RE.exec(line)
    if (match === null) continue
    if (match.slice(1).some((octet) => Number.parseInt(octet, 10) > 255)) continue
    if (!out.includes(line)) out.push(line)
  }
  return out
}

const POWERSHELL = 'powershell.exe'

/**
 * Addresses only: no table, no header, no localized label — a translated
 * Windows produces byte-identical output, one IPv4 address per line.
 */
const PS_ARGS = [
  '-NoProfile',
  '-NonInteractive',
  '-ExecutionPolicy',
  'Bypass',
  '-Command',
  'Get-DnsClientServerAddress -AddressFamily IPv4 | ForEach-Object { $_.ServerAddresses }'
]

/**
 * The adapter's servers change when the network does, not by the second, while
 * every read pays a full PowerShell start. The answer — readable or not — is
 * reused for this long so the 15 s medium tier does not spawn four shells a
 * minute; the distro side of the card is re-read on every tick regardless.
 */
const WINDOWS_DNS_TTL_MS = 30000

export interface DnsDeps {
  run?: HostCommandRunner
  /** Reads the Windows-side .wslconfig; null when it does not exist. */
  readWindowsFile?: (path: string) => Promise<string | null>
  /** %USERPROFILE%; null when it cannot be resolved. */
  userProfile?: string | null
  ttlMs?: number
  now?: () => number
}

async function readWindowsConfig(path: string): Promise<string | null> {
  try {
    return decodeConfigFile(await readFile(path))
  } catch {
    // A missing .wslconfig is a fact about the system, not a collector failure.
    return null
  }
}

export interface DnsCollector {
  /** Satisfies WslProvider.getDns once bound to a runner. */
  collect(runner: DistroRunner, distro: string): Promise<DnsInfo>
}

export function createDnsCollector(deps: DnsDeps = {}): DnsCollector {
  const run = deps.run ?? runHostCommand
  const readWindowsFile = deps.readWindowsFile ?? readWindowsConfig
  const ttlMs = deps.ttlMs ?? WINDOWS_DNS_TTL_MS
  const now = deps.now ?? Date.now
  // null is a real answer here — "could not be read" — so freshness is tracked
  // separately instead of being inferred from the cached value.
  let cached: string[] | null = null
  let cachedAt = 0
  let hasCached = false

  const readTunneling = async (): Promise<boolean | null> => {
    const profile =
      deps.userProfile !== undefined ? deps.userProfile : (process.env.USERPROFILE ?? null)
    if (profile === null || profile === '') return null
    const text = await readWindowsFile(`${profile.replace(/[\\/]+$/, '')}\\.wslconfig`)
    // Undeclared is not "off": the default flipped between WSL releases, so an
    // absent key is unknown rather than a value this collector made up.
    return text === null ? null : boolValue(text, 'wsl2', 'dnsTunneling')
  }

  const readWindowsDns = async (): Promise<string[] | null> => {
    if (hasCached && now() - cachedAt < ttlMs) return cached
    try {
      cached = parseWindowsDnsServers(await run(POWERSHELL, PS_ARGS, POWERSHELL_TIMEOUT_MS))
    } catch {
      // A spawn failure or a timeout leaves the Windows side unknown, never an
      // empty list that would read like an adapter handing out no servers.
      cached = null
    }
    cachedAt = now()
    hasCached = true
    return cached
  }

  /** null when the distro side could not be read; the Windows side still stands. */
  const readDistroFacts = async (
    runner: DistroRunner,
    distro: string
  ): Promise<DistroDnsFacts | null> => {
    try {
      const res = await runner.runInDistro(distro, DNS_SCRIPT, { timeoutMs: RUNNER_TIMEOUT_MS })
      return res.timedOut ? null : parseDnsFacts(res.stdout)
    } catch (err) {
      if (err instanceof WslNotAvailableError) throw err
      return null
    }
  }

  return {
    async collect(runner: DistroRunner, distro: string): Promise<DnsInfo> {
      assertValidDistroName(distro)
      const [facts, tunneling, windowsDns] = await Promise.all([
        readDistroFacts(runner, distro),
        readTunneling(),
        readWindowsDns()
      ])

      const errors: string[] = []
      if (facts === null) {
        errors.push(`${RESOLV_CONF_PATH} could not be read inside the distribution`)
      }
      if (windowsDns === null) errors.push('The Windows DNS servers could not be read')

      return {
        resolvConfPath: RESOLV_CONF_PATH,
        isGeneratedSymlink: facts?.isGeneratedSymlink ?? null,
        generateResolvConf: facts?.generateResolvConf ?? null,
        dnsTunneling: tunneling,
        nameservers: facts?.nameservers ?? [],
        windowsAdapterDns: windowsDns ?? [],
        error: errors.length === 0 ? null : errors.join('; ')
      }
    }
  }
}
